// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ1GA-C5NkkVG6Ff5ucHQEW1-aNzesGuc',
    appId: '1:1081307550699:web:daf2b4930228fbb78cffae',
    messagingSenderId: '1081307550699',
    projectId: 'chatappp-b8d77',
    authDomain: 'chatappp-b8d77.firebaseapp.com',
    storageBucket: 'chatappp-b8d77.appspot.com',
    measurementId: 'G-Y4VP9DSNLC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7B5DJM8FK2O670Dq83_THdUWAYbXiDOY',
    appId: '1:1081307550699:android:c5815d38d8e5def08cffae',
    messagingSenderId: '1081307550699',
    projectId: 'chatappp-b8d77',
    storageBucket: 'chatappp-b8d77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfMdvVrkpUPkJhnEIbGPtIL9woudmeoDM',
    appId: '1:1081307550699:ios:83387e39f64fc61e8cffae',
    messagingSenderId: '1081307550699',
    projectId: 'chatappp-b8d77',
    storageBucket: 'chatappp-b8d77.appspot.com',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfMdvVrkpUPkJhnEIbGPtIL9woudmeoDM',
    appId: '1:1081307550699:ios:83387e39f64fc61e8cffae',
    messagingSenderId: '1081307550699',
    projectId: 'chatappp-b8d77',
    storageBucket: 'chatappp-b8d77.appspot.com',
    iosBundleId: 'com.example.flutterApplication33',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZ1GA-C5NkkVG6Ff5ucHQEW1-aNzesGuc',
    appId: '1:1081307550699:web:7e63b83a28d147b58cffae',
    messagingSenderId: '1081307550699',
    projectId: 'chatappp-b8d77',
    authDomain: 'chatappp-b8d77.firebaseapp.com',
    storageBucket: 'chatappp-b8d77.appspot.com',
    measurementId: 'G-8R8QV44SXK',
  );
}
